movies = [
  { title: "Eternal Sunshine of the Spotless Mind", genre: "Drama/Romance", mood_tags: "heartbreak,sad,love,loss", description: "A couple erases each other from their memories after a painful breakup.", poster_url: "", rating: 8.3 },
  { title: "The Secret Life of Walter Mitty", genre: "Adventure/Drama", mood_tags: "lost,hopeful,adventure,motivation", description: "A daydreamer embarks on an unexpected journey of self-discovery.", poster_url: "", rating: 7.3 },
  { title: "Interstellar", genre: "Sci-Fi", mood_tags: "wonder,existential,epic,deep", description: "Astronauts travel through a wormhole in search of a new home for humanity.", poster_url: "", rating: 8.6 },
  { title: "Soul", genre: "Animation/Drama", mood_tags: "existential,hopeful,lost,meaning", description: "A musician discovers what it truly means to have a soul.", poster_url: "", rating: 8.1 },
  { title: "Superbad", genre: "Comedy", mood_tags: "happy,funny,bored,social", description: "Two best friends try to make the most of their last days of high school.", poster_url: "", rating: 7.6 },
  { title: "La La Land", genre: "Musical/Romance", mood_tags: "heartbreak,love,nostalgic,bittersweet", description: "A jazz musician and an actress fall in love while chasing their dreams.", poster_url: "", rating: 8.0 },
  { title: "The Social Network", genre: "Drama", mood_tags: "motivated,ambitious,focused,studying", description: "The story of how Facebook was founded.", poster_url: "", rating: 7.8 },
  { title: "Spirited Away", genre: "Animation/Fantasy", mood_tags: "wonder,escape,anxious,cozy", description: "A young girl wanders into a world of spirits and must find her way back.", poster_url: "", rating: 8.6 },
  { title: "Good Will Hunting", genre: "Drama", mood_tags: "lost,heartbreak,motivated,deep", description: "A janitor with a gift for mathematics resists the opportunities available to him.", poster_url: "", rating: 8.3 },
  { title: "The Grand Budapest Hotel", genre: "Comedy/Adventure", mood_tags: "bored,funny,quirky,cozy", description: "A legendary concierge and his protégé become embroiled in a murder mystery.", poster_url: "", rating: 8.1 },
  { title: "Her", genre: "Sci-Fi/Romance", mood_tags: "lonely,love,existential,heartbreak", description: "A man falls in love with an AI operating system.", poster_url: "", rating: 8.0 },
  { title: "Whiplash", genre: "Drama/Music", mood_tags: "motivated,ambitious,stressed,focused", description: "A music student pushes his limits under an abusive instructor.", poster_url: "", rating: 8.5 },
  { title: "Everything Everywhere All at Once", genre: "Sci-Fi/Comedy", mood_tags: "overwhelmed,existential,funny,family", description: "A woman discovers she must connect with parallel universe versions of herself.", poster_url: "", rating: 7.8 },
  { title: "Princess Mononoke", genre: "Animation/Fantasy", mood_tags: "epic,adventure,angry,wonder", description: "A prince becomes embroiled in a struggle between forest gods and humans.", poster_url: "", rating: 8.4 },
  { title: "About Time", genre: "Romance/Drama", mood_tags: "heartbreak,love,cozy,hopeful,family", description: "A man with the ability to time travel tries to find love and happiness.", poster_url: "", rating: 7.8 },
  { title: "Mad Max: Fury Road", genre: "Action", mood_tags: "angry,adventure,dark,intense", description: "A woman rebels against a tyrannical ruler in a post-apocalyptic wasteland.", poster_url: "", rating: 8.1 },
  { title: "John Wick", genre: "Action/Thriller", mood_tags: "angry,dark,revenge,intense", description: "An ex-hitman comes out of retirement to track down the gangsters who killed his dog.", poster_url: "", rating: 7.4 },
  { title: "Inside Out", genre: "Animation/Drama", mood_tags: "sad,family,nostalgic,hopeful,funny", description: "A young girl's emotions come to life as she navigates a big life change.", poster_url: "", rating: 8.1 },
  { title: "The Notebook", genre: "Romance/Drama", mood_tags: "romantic,heartbreak,love,nostalgic", description: "A poor young man and a rich young woman fall in love during the 1940s.", poster_url: "", rating: 7.8 },
  { title: "Parasite", genre: "Thriller/Drama", mood_tags: "dark,angry,existential,intense", description: "A poor family schemes to become employed by a wealthy family.", poster_url: "", rating: 8.5 },
  { title: "The Dark Knight", genre: "Action/Thriller", mood_tags: "dark,angry,intense,existential", description: "Batman faces the Joker, a criminal mastermind who wants to plunge Gotham into anarchy.", poster_url: "", rating: 9.0 },
  { title: "Clueless", genre: "Comedy/Romance", mood_tags: "happy,funny,romantic,bored", description: "A rich high schooler tries to boost a new student's popularity.", poster_url: "", rating: 6.9 },
  { title: "Chef", genre: "Comedy/Drama", mood_tags: "hopeful,motivated,funny,family", description: "A chef who loses his restaurant job starts a food truck with his son.", poster_url: "", rating: 7.3 },
  { title: "Promising Young Woman", genre: "Thriller/Drama", mood_tags: "angry,dark,revenge,motivated", description: "A woman seeks revenge against those who wronged her friend.", poster_url: "", rating: 7.5 },
  { title: "Nightcrawler", genre: "Thriller/Drama", mood_tags: "dark,angry,motivated,intense", description: "A driven man enters the world of crime journalism in LA.", poster_url: "", rating: 7.9 },
  { title: "Gone Girl", genre: "Thriller/Drama", mood_tags: "dark,angry,intense,existential", description: "A man becomes the prime suspect when his wife mysteriously disappears.", poster_url: "", rating: 8.1 },
  { title: "Before Sunrise", genre: "Romance/Drama", mood_tags: "romantic,existential,hopeful,wonder", description: "Two strangers spend one night together in Vienna before going their separate ways.", poster_url: "", rating: 8.1 },
  { title: "Crazy Rich Asians", genre: "Romance/Comedy", mood_tags: "romantic,happy,funny,family", description: "A woman discovers her boyfriend is from a very wealthy family.", poster_url: "", rating: 6.9 },
  { title: "Pride and Prejudice", genre: "Romance/Drama", mood_tags: "romantic,nostalgic,cozy,heartbreak", description: "Sparks fly between a headstrong woman and a wealthy, proud man.", poster_url: "", rating: 7.8 },
  { title: "10 Things I Hate About You", genre: "Romance/Comedy", mood_tags: "romantic,funny,happy,bored", description: "A girl can only date when her difficult older sister does too.", poster_url: "", rating: 7.3 },
  { title: "When Harry Met Sally", genre: "Romance/Comedy", mood_tags: "romantic,funny,nostalgic,hopeful", description: "Two friends debate whether men and women can ever just be friends.", poster_url: "", rating: 7.6 },
  { title: "Black Swan", genre: "Thriller/Drama", mood_tags: "dark,anxious,existential,intense", description: "A ballet dancer's obsession with perfection leads to her undoing.", poster_url: "", rating: 8.0 },
  { title: "Requiem for a Dream", genre: "Drama", mood_tags: "dark,sad,existential,lost", description: "Four people's lives spiral out of control due to addiction.", poster_url: "", rating: 8.3 },
  { title: "Se7en", genre: "Thriller/Crime", mood_tags: "dark,intense,existential,angry", description: "Two detectives hunt a serial killer using the seven deadly sins.", poster_url: "", rating: 8.6 },
  { title: "Prisoners", genre: "Thriller/Drama", mood_tags: "dark,anxious,intense,angry", description: "A father takes matters into his own hands when his daughter goes missing.", poster_url: "", rating: 8.1 },
  { title: "The Incredibles", genre: "Animation/Action", mood_tags: "family,funny,adventure,happy", description: "A family of superheroes must save the world while keeping their powers secret.", poster_url: "", rating: 8.0 },
  { title: "Coco", genre: "Animation/Drama", mood_tags: "family,nostalgic,sad,hopeful,wonder", description: "A boy accidentally enters the Land of the Dead and discovers his family history.", poster_url: "", rating: 8.4 },
  { title: "Paddington 2", genre: "Comedy/Family", mood_tags: "family,funny,cozy,happy,hopeful", description: "Paddington Bear is wrongfully jailed and must clear his name.", poster_url: "", rating: 7.8 },
  { title: "Hunt for the Wilderpeople", genre: "Comedy/Adventure", mood_tags: "family,funny,adventure,hopeful,lost", description: "A misfit boy and his grumpy foster uncle go on the run in the NZ wilderness.", poster_url: "", rating: 7.9 },
  { title: "Game Night", genre: "Comedy/Thriller", mood_tags: "funny,happy,bored,adventure", description: "A group of friends' game night turns into a real-life mystery.", poster_url: "", rating: 7.0 },
  { title: "The Nice Guys", genre: "Comedy/Crime", mood_tags: "funny,dark,adventure,bored", description: "A mismatched pair of private eyes investigate a missing girl in 1970s LA.", poster_url: "", rating: 7.4 },
  { title: "Knives Out", genre: "Comedy/Mystery", mood_tags: "funny,dark,existential,bored", description: "A detective investigates the death of a wealthy crime novelist.", poster_url: "", rating: 7.9 },
  { title: "What We Do in the Shadows", genre: "Comedy/Horror", mood_tags: "funny,dark,bored,quirky", description: "A documentary crew follows a group of vampire flatmates in New Zealand.", poster_url: "", rating: 7.6 },
  { title: "Billy Elliot", genre: "Drama", mood_tags: "hopeful,motivated,family,lost,angry", description: "A boy in a mining town discovers a passion for ballet dancing.", poster_url: "", rating: 7.7 },
  { title: "The Pursuit of Happyness", genre: "Drama", mood_tags: "motivated,hopeful,sad,family,lost", description: "A struggling salesman takes custody of his son and chases his dream.", poster_url: "", rating: 8.0 },
  { title: "Eddie the Eagle", genre: "Comedy/Drama", mood_tags: "funny,hopeful,motivated,happy", description: "The story of Britain's first Olympic ski jumper against all odds.", poster_url: "", rating: 7.4 },
  { title: "Julie & Julia", genre: "Drama/Comedy", mood_tags: "cozy,hopeful,motivated,nostalgic", description: "Two women separated by decades bond over their love of French cooking.", poster_url: "", rating: 6.9 },
  { title: "Amélie", genre: "Romance/Comedy", mood_tags: "cozy,romantic,wonder,nostalgic,funny", description: "A shy Parisian woman decides to change the lives of those around her.", poster_url: "", rating: 8.3 },
  { title: "My Neighbor Totoro", genre: "Animation/Family", mood_tags: "cozy,family,wonder,happy,nostalgic", description: "Two sisters move to the country and encounter magical forest spirits.", poster_url: "", rating: 8.1 },
  { title: "The Tree of Life", genre: "Drama", mood_tags: "existential,wonder,nostalgic,sad,family", description: "A family in 1950s Texas grapples with life, loss and the meaning of existence.", poster_url: "", rating: 6.8 },
  { title: "Arrival", genre: "Sci-Fi/Drama", mood_tags: "existential,wonder,sad,deep,hopeful", description: "A linguist works to communicate with aliens who have landed on Earth.", poster_url: "", rating: 7.9 },
  { title: "2001: A Space Odyssey", genre: "Sci-Fi", mood_tags: "existential,wonder,dark,deep", description: "Humanity finds a mysterious artifact and sets out on a mission to Jupiter.", poster_url: "", rating: 8.3 },
  { title: "Breakfast at Tiffany's", genre: "Romance/Drama", mood_tags: "romantic,nostalgic,cozy,lost", description: "A young New York socialite falls for a writer despite her impractical lifestyle.", poster_url: "", rating: 7.6 },
  { title: "The Graduate", genre: "Drama/Romance", mood_tags: "lost,existential,nostalgic,heartbreak", description: "A disillusioned college graduate has an affair with an older woman.", poster_url: "", rating: 8.0 },
  { title: "Psycho", genre: "Thriller/Horror", mood_tags: "dark,anxious,intense,existential", description: "A secretary on the run ends up at a remote motel with a disturbed owner.", poster_url: "", rating: 8.5 },
  { title: "Lawrence of Arabia", genre: "Adventure/Drama", mood_tags: "adventure,wonder,epic,existential", description: "The story of T.E. Lawrence and his role in the Arab revolt against the Ottomans.", poster_url: "", rating: 8.3 },
  { title: "Dr. Strangelove", genre: "Comedy/Satire", mood_tags: "funny,dark,existential,angry", description: "A paranoid general triggers a nuclear crisis and the president scrambles to stop it.", poster_url: "", rating: 8.4 },
  { title: "The Good the Bad and the Ugly", genre: "Western", mood_tags: "adventure,dark,angry,epic", description: "Three gunslingers compete to find a buried cache of Confederate gold.", poster_url: "", rating: 8.8 },
  { title: "The Godfather", genre: "Crime/Drama", mood_tags: "dark,family,angry,intense,epic", description: "The aging patriarch of an organized crime dynasty transfers control to his son.", poster_url: "", rating: 9.2 },
  { title: "Taxi Driver", genre: "Drama/Thriller", mood_tags: "dark,lonely,angry,existential,lost", description: "A mentally unstable veteran works as a night-time taxi driver in New York.", poster_url: "", rating: 8.2 },
  { title: "Annie Hall", genre: "Romance/Comedy", mood_tags: "romantic,funny,nostalgic,heartbreak,existential", description: "A neurotic New York comedian reflects on his failed relationship.", poster_url: "", rating: 8.0 },
  { title: "Rocky", genre: "Drama/Sport", mood_tags: "motivated,hopeful,family,angry,epic", description: "A small-time boxer gets a shot at the heavyweight championship.", poster_url: "", rating: 8.1 },
  { title: "Jaws", genre: "Thriller/Adventure", mood_tags: "anxious,dark,adventure,intense", description: "A massive shark terrorizes a beach town and three men set out to stop it.", poster_url: "", rating: 8.0 },
  { title: "Star Wars: A New Hope", genre: "Sci-Fi/Adventure", mood_tags: "adventure,wonder,hopeful,epic,family", description: "A young farm boy joins a rebellion to defeat an evil galactic empire.", poster_url: "", rating: 8.6 },
  { title: "Apocalypse Now", genre: "War/Drama", mood_tags: "dark,existential,angry,intense,epic", description: "A soldier is sent to assassinate a rogue colonel deep in the jungle.", poster_url: "", rating: 8.4 },
  { title: "E.T. the Extra-Terrestrial", genre: "Family/Sci-Fi", mood_tags: "family,wonder,hopeful,nostalgic,sad", description: "A lonely boy befriends an alien stranded on Earth.", poster_url: "", rating: 7.9 },
  { title: "Back to the Future", genre: "Sci-Fi/Comedy", mood_tags: "adventure,funny,hopeful,nostalgic,family", description: "A teenager is accidentally sent back to 1955 in a time-traveling DeLorean.", poster_url: "", rating: 8.5 },
  { title: "The Breakfast Club", genre: "Drama/Comedy", mood_tags: "lost,nostalgic,angry,existential,funny", description: "Five high school students from different cliques spend Saturday detention together.", poster_url: "", rating: 7.9 },
  { title: "Ferris Bueller's Day Off", genre: "Comedy", mood_tags: "funny,happy,bored,adventure,nostalgic", description: "A high school senior tricks his friends into skipping school for one last adventure.", poster_url: "", rating: 7.8 },
  { title: "Raiders of the Lost Ark", genre: "Adventure/Action", mood_tags: "adventure,funny,wonder,epic,happy", description: "An archaeologist races against Nazis to find the legendary Ark of the Covenant.", poster_url: "", rating: 8.4 },
  { title: "Blade Runner", genre: "Sci-Fi/Thriller", mood_tags: "dark,existential,wonder,lonely,intense", description: "A detective hunts down rogue androids in a dystopian future Los Angeles.", poster_url: "", rating: 8.1 },
  { title: "Die Hard", genre: "Action/Thriller", mood_tags: "adventure,funny,angry,intense,happy", description: "A cop single-handedly takes on a group of terrorists in a Los Angeles skyscraper.", poster_url: "", rating: 8.2 },
  { title: "When Harry Met Sally", genre: "Romance/Comedy", mood_tags: "romantic,funny,nostalgic,hopeful,heartbreak", description: "Two friends debate whether men and women can ever just be friends.", poster_url: "", rating: 7.6 },
  { title: "Stand By Me", genre: "Adventure/Drama", mood_tags: "nostalgic,adventure,family,sad,hopeful", description: "Four boys go on a journey to find a dead body in the Oregon wilderness.", poster_url: "", rating: 8.1 },
  { title: "Schindler's List", genre: "Drama/History", mood_tags: "sad,dark,hopeful,existential,epic", description: "A German businessman saves the lives of more than a thousand Jewish refugees.", poster_url: "", rating: 9.0 },
  { title: "Forrest Gump", genre: "Drama/Romance", mood_tags: "hopeful,nostalgic,sad,funny,family", description: "A slow-witted but kind man witnesses and influences major historical events.", poster_url: "", rating: 8.8 },
  { title: "Pulp Fiction", genre: "Crime/Drama", mood_tags: "dark,funny,intense,existential,bored", description: "The lives of two mob hitmen, a boxer, and others interweave in LA.", poster_url: "", rating: 8.9 },
  { title: "The Lion King", genre: "Animation/Family", mood_tags: "family,sad,hopeful,epic,nostalgic", description: "A young lion prince flees his kingdom after his father's murder.", poster_url: "", rating: 8.5 },
  { title: "Groundhog Day", genre: "Comedy/Romance", mood_tags: "funny,existential,romantic,hopeful,bored", description: "A weatherman finds himself reliving the same day over and over again.", poster_url: "", rating: 8.0 },
  { title: "The Shawshank Redemption", genre: "Drama", mood_tags: "hopeful,sad,dark,existential,motivated", description: "Two imprisoned men bond over years finding solace and redemption.", poster_url: "", rating: 9.3 },
  { title: "Titanic", genre: "Romance/Drama", mood_tags: "romantic,heartbreak,sad,epic,nostalgic", description: "A young couple fall in love aboard the ill-fated RMS Titanic.", poster_url: "", rating: 7.9 },
  { title: "Jurassic Park", genre: "Sci-Fi/Adventure", mood_tags: "adventure,wonder,anxious,family,epic", description: "A theme park with cloned dinosaurs descends into chaos.", poster_url: "", rating: 8.2 },
  { title: "Clueless", genre: "Comedy/Romance", mood_tags: "funny,romantic,happy,nostalgic,bored", description: "A rich high schooler tries to boost a new student's popularity.", poster_url: "", rating: 6.9 },
  { title: "The Matrix", genre: "Sci-Fi/Action", mood_tags: "existential,wonder,dark,adventure,motivated", description: "A hacker discovers the world is a simulation and joins a rebellion.", poster_url: "", rating: 8.7 },
  { title: "Fight Club", genre: "Drama/Thriller", mood_tags: "dark,existential,angry,motivated,intense", description: "An insomniac and a soap salesman build an underground fight club.", poster_url: "", rating: 8.8 },
  { title: "American Beauty", genre: "Drama", mood_tags: "existential,dark,lost,nostalgic,angry", description: "A man has a midlife crisis and becomes infatuated with his daughter's friend.", poster_url: "", rating: 8.3 },
  { title: "Toy Story", genre: "Animation/Family", mood_tags: "family,funny,hopeful,nostalgic,adventure", description: "A cowboy toy is threatened when a new spaceman toy takes his place.", poster_url: "", rating: 8.3 },
  { title: "Home Alone", genre: "Comedy/Family", mood_tags: "funny,family,happy,nostalgic,adventure", description: "An eight-year-old is accidentally left behind when his family flies to France.", poster_url: "", rating: 7.7 },
  { title: "Goodfellas", genre: "Crime/Drama", mood_tags: "dark,angry,intense,motivated,epic", description: "The story of Henry Hill and his life in the mob.", poster_url: "", rating: 8.7 },
  { title: "Memento", genre: "Thriller/Mystery", mood_tags: "dark,existential,anxious,intense,lost", description: "A man with short-term memory loss tries to find his wife's murderer.", poster_url: "", rating: 8.4 },
  { title: "Cast Away", genre: "Drama/Adventure", mood_tags: "lost,existential,hopeful,sad,adventure", description: "A FedEx employee is stranded alone on a remote island for four years.", poster_url: "", rating: 7.8 },
  { title: "Moulin Rouge!", genre: "Musical/Romance", mood_tags: "romantic,heartbreak,sad,wonder,nostalgic", description: "A poet falls in love with a cabaret actress in 19th century Paris.", poster_url: "", rating: 7.6 },
  { title: "A Beautiful Mind", genre: "Drama/Biography", mood_tags: "motivated,existential,hopeful,anxious,wonder", description: "The story of mathematician John Nash's brilliance and his struggle with mental illness.", poster_url: "", rating: 8.2 },
  { title: "Lost in Translation", genre: "Drama/Romance", mood_tags: "lonely,nostalgic,existential,cozy,romantic", description: "Two Americans form an unlikely bond while staying at a Tokyo hotel.", poster_url: "", rating: 7.7 },
  { title: "Finding Nemo", genre: "Animation/Family", mood_tags: "family,funny,adventure,hopeful,wonder", description: "A clownfish searches the ocean to find his missing son.", poster_url: "", rating: 8.2 },
  { title: "Kill Bill Vol 1", genre: "Action/Thriller", mood_tags: "angry,dark,adventure,intense,motivated", description: "A former assassin seeks revenge against her ex-boss and his deadly team.", poster_url: "", rating: 8.2 },
  { title: "Eternal Sunshine of the Spotless Mind", genre: "Drama/Romance", mood_tags: "heartbreak,sad,love,loss,existential", description: "A couple erases each other from their memories after a painful breakup.", poster_url: "", rating: 8.3 },
  { title: "The Notebook", genre: "Romance/Drama", mood_tags: "romantic,heartbreak,nostalgic,sad,love", description: "A poor young man and a rich young woman fall in love in the 1940s.", poster_url: "", rating: 7.8 },
  { title: "No Country for Old Men", genre: "Thriller/Crime", mood_tags: "dark,intense,existential,anxious,angry", description: "A hunter stumbles upon drug money and is pursued by a relentless killer.", poster_url: "", rating: 8.2 },
  { title: "The Departed", genre: "Crime/Thriller", mood_tags: "dark,intense,angry,existential,epic", description: "An undercover cop and a mole in the police attempt to identify each other.", poster_url: "", rating: 8.5 },
  { title: "Pan's Labyrinth", genre: "Fantasy/Drama", mood_tags: "dark,wonder,sad,existential,adventure", description: "A girl escapes into a fantastical labyrinth during post-war Spain.", poster_url: "", rating: 8.2 },
  { title: "The Dark Knight", genre: "Action/Thriller", mood_tags: "dark,angry,intense,existential,epic", description: "Batman faces the Joker, a criminal mastermind who wants to plunge Gotham into anarchy.", poster_url: "", rating: 9.0 },
  { title: "WALL-E", genre: "Animation/Sci-Fi", mood_tags: "romantic,wonder,hopeful,sad,existential", description: "A robot falls in love and helps save humanity from environmental collapse.", poster_url: "", rating: 8.4 },
]

movies.each do |movie|
  Movie.find_or_create_by(title: movie[:title]) do |m|
    m.genre = movie[:genre]
    m.mood_tags = movie[:mood_tags]
    m.description = movie[:description]
    m.poster_url = movie[:poster_url]
    m.rating = movie[:rating]
  end
end

puts "#{Movie.count} movies seeded!"